### PR TITLE
Add "prevent proceed" feature to Branching Scenario

### PR DESCRIPTION
**Pull request by otacke**
# Add "prevent proceed" feature to Branching Scenario

This pull request will optionally allow authors of Branching Scenario to require users to "finish" a content node before the proceed button gets enabled.

Suggestions for the UX design are welcome -- and expected ;-)

The feature was requested at the "Technische Hochschule Lübeck", Germany.

This pull request is part of 2 separate pull requests for the branch "require-content-finished" of
- Branching Scenario
- Branching Scenario Editor

## Acceptance criteria
- Authors can enable/disable the "require finished" option in a behavioral settings group for each content node (default: feature is disabled)
- Authors can globally override enabling/disabling the "require finished" option in a behavioral settings group or use the individual settings per content (default: individual settings)
- Users need to finish a node before the proceed button gets enabled if set so
- "Proceed" button is enabled if there's no sensible action required for finishing

## Pull request details
- Add a "behavioural" setting to optionally enable the "require finish" option
- Add logic to go detect whether a content can require to be finished
  - general case: if the _getScore_ function of the question type contract is implemented, expect the xAPI statement _answered_/_completed_ to enable the proceed button
  - Audio/Video: expect the audio/video to trigger the "ended" event
  - Interactive Video: expect a result to be submitted if there are interactions, like regular video otherwise
  - Course Presentation: If there's more that one slide, expect the final slide to be reached (which will be the summary slide if it present and not disabled); no proceed requirements for active surface mode as it may not be obvious for the user where the "end" is, in particular counter-productive for the sample content of Branching Scenario
- Add logic/styles for enabling/disabling the proceed button
- Update translation files
- Add upgrades script to add new parameters
- Bump minor versions

## Possible future work
- Add button tooltip to explain why the "proceed" button is disabled: "You need to finish this content before you are allowed to proceed"
- Add option to expect the xapi statement property result.success to be true, so students can only proceed if the exercise has been successfully completed.

### CODE REVIEW

**Comment by thomasmars** [comment]
Thumbs up for "require fished" option :+1:

**Comment by otacke** [comment]
@thomasmars :-) Working on it again right now to add individual settings per node ...

**Comment by otacke** [comment]
@thomasmars Oh, now I see the typo :-D :-D :-D

**Comment by joeyzhouhaiyi** [comment]
Please merge it ASAP, we need this feature badly!  [._________.]

**Pull request merged**
